### PR TITLE
Be more verbose when gcov fails

### LINKED ISSUE #232: When gcov fails, output its stdout and stderr

### PR DESCRIPTION
**Pull request by marco-c**
Since I was here, I've also removed some useless commented-out code (in a separate commit).

Fixes #232.

### CODE REVIEW

File: src/gcov.rs [hunk 1]
```diff
@@ -51,21 +20,16 @@ pub fn run_gcov(gcno_path: &PathBuf, branch_enabled: bool, working_dir: &PathBuf
...
-        gcno_path.display()
-    );
-    //}
+    let output = status.output().expect("Failed to execute gcov process");
+
+    if !output.status.success() {
+        eprintln!("gcov stdout: {}", String::from_utf8_lossy(&output.stdout));
+        eprintln!("gcov stderr: {}", String::from_utf8_lossy(&output.stderr));
+
+        panic!("gcov wasn't successfully executed on {}", gcno_path.display());
```
Comment (sylvestre) [inline src/gcov.rs]: maybe improve the wording with 
gcov execution failed on {}

Comment (marco-c) [reply src/gcov.rs]: Good idea, done with dba3edcf581a6f46e13d4ec4d2086809b87fc0d6.
