### PR TITLE
Exit with 1 when a thread is panicking

### LINKED ISSUE #215: If a thread fails, the error code should not be 0
```
marco@marco ~/Documenti $ grcov jsvm/file.info 
thread '<unnamed>' panicked at 'No input files found', src/producer.rs:425:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
marco@marco ~/Documenti $ echo $?
0
```

### PR DESCRIPTION
**Pull request by calixteman**
Fixes #215.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -297,15 +297,25 @@ fn main() {
         parsers.push(t);
     }
 
-    let _ = producer.join();
+    match producer.join() {
```
Comment (marco-c) [inline src/main.rs]: Nit: you could use if-let in cases like this:
```Rust
if let Err(_) = producer.join() {
  ...
}
```
