### PR TITLE
Fix cobertura report for multiple files

### LINKED ISSUE #636: Cobertura report has wrong summary of lines coverage
We started to use cobertura reports for code coverage in a project on GitLab: https://gitlab.com/svenfoo/sparschwein

The numbers reported on the `coverage` element do not seem to make much sense though:

     <coverage lines-covered="103" lines-valid="116"  ... >

There are certainly more than 116 lines in the code base. The XML lists several packages, each with lines that should sum up to something like 750 lines (counted with `wc -l` so that number might be off, but you get the point).

I had a look at the code in `cobertura.rs` and it seems to collect the total number of lines, and the number of covered lines, by calling `self.packages.get_lines()`. That is implemented as a Trait on `Vec<T>` and as far as I understand the implementation it pushes the lines of all packages into a single `FxHashMap` using the line number as the key. Is that right? 

If my interpretation of the code is right, then lines with the same number would be handled as the same line. That would then explain the result, as lines from different files (packages) would collide, leaving only about the number of lines in the largest package in the resulting hashmap.

Of course my interpretation of the code might be totally wrong. But still the reported numbers do not seem to reflect the number of lines in the code base. I got skeptical when the reported line coverage went down after I added more tests.

I am attaching the cobertura report here:
[coverage.xml.gz](https://github.com/mozilla/grcov/files/6626699/coverage.xml.gz)

### PR DESCRIPTION
**Pull request by svenfoo**
Fix the implementation of `Coverage::get_stats()` so that it doesn't create it from a merged hash of all lines from all packages, but instead adds up the the `Stats` of all packages.

Fixes #636

### CODE REVIEW

File: src/cobertura.rs [hunk 1]
```diff
@@ -41,6 +42,20 @@ struct CoverageStats {
     complexity: f64,
 }
 
+impl std::ops::Add for CoverageStats {
```
Comment (svenfoo) [inline src/cobertura.rs:45]: This could be derived using https://crates.io/crates/derive_more. Just let me know if you would prefer that.

**Review by marco-c — APPROVED** [review]
Thanks!
