### PR TITLE
Fail if llvm-profdata is innaccessible

### LINKED ISSUE #662: Bypassing the error
I'm using the source-based Rust coverage but occasionally forgot to install an `llvm-tools-preview` component.
In CI I got the green job with no coverage, but in fact, one error passed unnoticed on `grcov` side:

<details>

```
test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.24s
$ grcov . --binary-path ./target/debug/ --source-dir . --output-type lcov --llvm --branch --ignore-not-existing --ignore "/*" --ignore "tests/*" --output-path lcov-w-branch.info
16:34:00 [ERROR] Error while executing llvm tools: Failed to execute "/usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata" ...

# many file names

...
"/tmp/.tmps2z62Q/crates/lang/llvmcoveragedata-6052-17221853374265077399_0_1.profraw" "-o" "/tmp/.tmps2z62Q/0/grcov.profdata"
No such file or directory (os error 2)

$ rust-covfix lcov-w-branch.info --output lcov-w-branch-fixed.info
Coverages are fixed successfully!
  line:   NaN% (0 of 0 lines)    => NaN% (0 of 0 lines)
  branch: NaN% (0 of 0 branches) => NaN% (0 of 0 branches)
```

</details>

I didn't find a flag to specify an exit code.

CC: https://github.com/mozilla/grcov/issues/656 https://github.com/mozilla/grcov/issues/555

### PR DESCRIPTION
**Pull request by lincolnauster**
If the toolchain is improperly set up and the requisite cargo tools are innacessible, grcov currently errors out, but with an exit code of 0. This primarily causes false successes in CI.

I've patched this fork to propogate an error (and thus return non-zero) if the path located doesn't exist.

Two questions:

+ This is a potentially breaking change, and I'm not sure how this project handles documentation - I don't see a CHANGELOG in the root. Where should this be documented?
+ This is untestable with `cargo t`. Is it a small enough change that testing isn't useful, or should I/we figure something out in the CI pipeline?

Fixes #662.

### CODE REVIEW

**Comment by lincolnauster** [comment]
^ Hm, can't locally replicate the test failures; not sure what's going on there.

File: src/llvm_tools.rs [hunk 1]
```diff
@@ -78,6 +79,18 @@ pub fn profraws_to_lcov(
     Ok(results)
 }
 
+fn get_profdata_path() -> Result<PathBuf, String> {
+    let path = Tool::Profdata.path().map_err(|x| x.to_string())?;
+    if !path.exists() {
+        Err(String::from(
+            "We couldn't find llvm-profdata. \
+             Do you have the llvm-tools component installed?"
```
Comment (marco-c) [inline src/llvm_tools.rs:87]: Nit: can you also say how to install it?

**Comment by marco-c** [comment]
> This is a potentially breaking change, and I'm not sure how this project handles documentation - I don't see a CHANGELOG in the root. Where should this be documented?

We are currently not documenting such changes, we only document the current state of things in the README.

> This is untestable with cargo t. Is it a small enough change that testing isn't useful, or should I/we figure something out in the CI pipeline?

Yeah, I think this is small enough and difficult enough to test that we can accept it without tests.

> ^ Hm, can't locally replicate the test failures; not sure what's going on there.

We are in the middle of moving from Travis to GitHub Actions (it's taking a while), so these failures are expected.

File: src/llvm_tools.rs (hunk 1 above)
Comment (lincolnauster) [reply src/llvm_tools.rs]: Definitely, added in b2ac731

**Comment by lincolnauster** [comment]
> > This is a potentially breaking change, and I'm not sure how this project handles documentation - I don't see a CHANGELOG in the root. Where should this be documented?
> 
> We are currently not documenting such changes, we only document the current state of things in the README.
> 
> > This is untestable with cargo t. Is it a small enough change that testing isn't useful, or should I/we figure something out in the CI pipeline?
> 
> Yeah, I think this is small enough and difficult enough to test that we can accept it without tests.
> 
> > ^ Hm, can't locally replicate the test failures; not sure what's going on there.
> 
> We are in the middle of moving from Travis to GitHub Actions (it's taking a while), so these failures are expected.

Sounds good, thanks for looking at this!

**Review by marco-c — APPROVED** [review]
